# Generated by Django 2.1.2 on 2018-12-12 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mappings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', related_query_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='예매자'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='mappings.Movie', verbose_name='영화'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='mappings.Theater', verbose_name='소속 영화관'),
        ),
    ]
