# Generated by Django 2.1.2 on 2018-12-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('seats_no', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '상영관',
                'verbose_name_plural': '상영관 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=30, null=True)),
                ('cast', models.CharField(blank=True, max_length=128, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('trailer', models.URLField(blank=True, default='', null=True)),
                ('reservation_score', models.FloatField(blank=True, default=0, null=True)),
                ('now_show', models.BooleanField(blank=True, default=False, null=True)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to=reservations.models.main_directory_path)),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Movie')),
            ],
            options={
                'verbose_name': '상영',
                'verbose_name_plural': '상영 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_times', to='reservations.Screening')),
            ],
            options={
                'verbose_name': '상영 시간',
                'verbose_name_plural': '상영 시간 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('reservation_check', models.BooleanField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Auditorium')),
            ],
            options={
                'verbose_name': '좌석',
                'verbose_name_plural': '좌석 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SelectedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_seats', to='reservations.Reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Seat')),
            ],
            options={
                'verbose_name': '선택 좌석',
                'verbose_name_plural': '선택 좌석 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Stillcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reservations.models.still_cut_directory_path)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stillcuts', to='reservations.Movie')),
            ],
            options={
                'verbose_name': '스틸컷',
                'verbose_name_plural': '스틸컷 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('sub_location', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('current_movies', models.ManyToManyField(related_name='theaters', related_query_name='theater', through='reservations.Screening', to='reservations.Movie')),
            ],
            options={
                'verbose_name': '극장',
                'verbose_name_plural': '극장 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='screening',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Theater'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Screening'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ScreeningTime'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Theater'),
        ),
    ]
