# Generated by Django 2.1.2 on 2018-12-04 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=64, null=True, verbose_name='배우')),
            ],
            options={
                'verbose_name': '배우',
                'verbose_name_plural': '배우 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name',
            field=models.CharField(max_length=10, verbose_name='상영관 이름'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='seats_no',
            field=models.IntegerField(default=0, verbose_name='좌석 수'),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Theater', verbose_name='소속 영화관'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='줄거리'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=reservations.models.main_directory_path, verbose_name='메인 포스터'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='now_show',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='상영 여부'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='개봉일'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reservation_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='예매율'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='타이틀'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, default='', null=True, verbose_name='트레일러'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Screening', verbose_name='상영 예매'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='screening_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ScreeningTime', verbose_name='예매 시간'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='예매자'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Auditorium', verbose_name='상영관'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Movie', verbose_name='상영 영화'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Theater', verbose_name='상영 영화관'),
        ),
        migrations.AlterField(
            model_name='screeningtime',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_times', to='reservations.Screening', verbose_name='상영'),
        ),
        migrations.AlterField(
            model_name='screeningtime',
            name='time',
            field=models.DateTimeField(verbose_name='상영 시간'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Auditorium', verbose_name='배치 상영관'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(verbose_name='열'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='reservation_check',
            field=models.BooleanField(verbose_name='예매 여부'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(verbose_name='행'),
        ),
        migrations.AlterField(
            model_name='selectedseat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_seats', to='reservations.Reservation', verbose_name='예약'),
        ),
        migrations.AlterField(
            model_name='selectedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Seat', verbose_name='좌석'),
        ),
        migrations.AlterField(
            model_name='stillcut',
            name='image',
            field=models.ImageField(upload_to=reservations.models.still_cut_directory_path, verbose_name='스틸컷 이미지'),
        ),
        migrations.AlterField(
            model_name='stillcut',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stillcuts', to='reservations.Movie', verbose_name='영화'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.CharField(max_length=50, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='current_movies',
            field=models.ManyToManyField(related_name='theaters', related_query_name='theater', through='reservations.Screening', to='reservations.Movie', verbose_name='상영 영화'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='location',
            field=models.CharField(max_length=10, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='sub_location',
            field=models.CharField(max_length=15, verbose_name='지점'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='reservations.Movie', verbose_name='영화'),
        ),
    ]
